source 'https://github.com/CocoaPods/Specs.git'

target 'CommonUtilsAds', :exclusive => true do
  pod "CommonUtilsAds", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CommonUtilsAds", :path => "../"

  pod 'FBSnapshotTestCase'
end
